### ISSUE TITLE
pip install creates only the  dist-info not the package.

### ISSUE THREAD

**Issue by yulijia** [epurdom/cobolt#5]
Hi

I meet a very strange issue, when I install the `cobolt` package via pip,  it creates only the dist-info not the package.

Does anyone know how to correctly install this package?

```
> pip install git+https://github.com/boyinggong/cobolt.git#egg=cobolt
Collecting cobolt
  Cloning https://github.com/boyinggong/cobolt.git to /tmp/pip-install-ofckrcm6/cobolt_eab4792b4a4a423193ff1c211c10a4d5
  Running command git clone --filter=blob:none -q https://github.com/boyinggong/cobolt.git /tmp/pip-install-ofckrcm6/cobolt_eab4792b4a4a423193ff1c211c10a4d5
  Resolved https://github.com/boyinggong/cobolt.git to commit 7bb186d7ab8ad2e08d42a2ce79e20f2b07dc43cc
  Preparing metadata (setup.py) ... done
Collecting numpy
  Using cached numpy-1.21.5-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
Collecting scipy
  Using cached scipy-1.7.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (38.1 MB)
Collecting torch
  Using cached torch-1.10.1-cp37-cp37m-manylinux1_x86_64.whl (881.9 MB)
Collecting umap-learn
  Using cached umap_learn-0.5.2-py3-none-any.whl
Collecting python-igraph
  Using cached python_igraph-0.9.9-py3-none-any.whl (9.1 kB)
Collecting sklearn
  Using cached sklearn-0.0-py2.py3-none-any.whl
Collecting xgboost
  Using cached xgboost-1.5.1-py3-none-manylinux2014_x86_64.whl (173.5 MB)
Collecting igraph==0.9.9
  Using cached igraph-0.9.9-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
Collecting texttable>=1.6.2
  Using cached texttable-1.6.4-py2.py3-none-any.whl (10 kB)
Collecting scikit-learn
  Using cached scikit_learn-1.0.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (24.8 MB)
Collecting typing-extensions
  Using cached typing_extensions-4.0.1-py3-none-any.whl (22 kB)
Collecting numba>=0.49
  Using cached numba-0.54.1-cp37-cp37m-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.3 MB)
Collecting tqdm
  Using cached tqdm-4.62.3-py2.py3-none-any.whl (76 kB)
Collecting pynndescent>=0.5
  Using cached pynndescent-0.5.5-py3-none-any.whl
Requirement already satisfied: setuptools in /dskh/nobackup/lijiay/miniconda3/envs/Cobolt/lib/python3.7/site-packages (from numba>=0.49->umap-learn->cobolt) (60.5.0)
Collecting llvmlite<0.38,>=0.37.0rc1
  Using cached llvmlite-0.37.0-cp37-cp37m-manylinux2014_x86_64.whl (26.3 MB)
Collecting numpy
  Using cached numpy-1.20.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.3 MB)
Collecting joblib>=0.11
  Using cached joblib-1.1.0-py2.py3-none-any.whl (306 kB)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-3.0.0-py3-none-any.whl (14 kB)
Building wheels for collected packages: cobolt
  Building wheel for cobolt (setup.py) ... done
  Created wheel for cobolt: filename=cobolt-0.0.1-py3-none-any.whl size=29564 sha256=a1296b8af4fb43d2165cb63215c0e6b3d6a23363c452d7a3228fbcaf84a00c7a
  Stored in directory: /tmp/pip-ephem-wheel-cache-qmb0y40t/wheels/2c/c9/bc/f04eb1e7aad1d22d0f11487844d7b1f6c20733f38326307d1d
Successfully built cobolt
Installing collected packages: numpy, threadpoolctl, scipy, llvmlite, joblib, texttable, scikit-learn, numba, typing-extensions, tqdm, pynndescent, igraph, xgboost, umap-learn, torch, sklearn, python-igraph, cobolt
Successfully installed cobolt-0.0.1 igraph-0.9.9 joblib-1.1.0 llvmlite-0.37.0 numba-0.54.1 numpy-1.20.3 pynndescent-0.5.5 python-igraph-0.9.9 scikit-learn-1.0.2 scipy-1.7.3 sklearn-0.0 texttable-1.6.4 threadpoolctl-3.0.0 torch-1.10.1 tqdm-4.62.3 typing-extensions-4.0.1 umap-learn-0.5.2 xgboost-1.5.1

```

```
> ls ./lib/python3.7/site-packages | grep cobolt
cobolt-0.0.1.dist-info
```

**Comment by boyinggong** [comment]
Hi,

Thanks for trying out the package. We have updated the installation link, would you mind trying the updated command? That is, replacing `boyinggong` in the link with `epurdom`.

Thanks,
Boying

**Comment by Chengwei94** [comment]
@boyinggong  I have the same issue with the new link, I think the setup.py only install the subdirectories of cobolt and not cobolt itself

**Comment by boyinggong** [comment]
@Chengwei94 Updated the setup file. This has now been fixed.

**Comment by WhaleGe** [comment]
@boyinggong hello，I can't install cobolt until now. Has the setup file been updated? I have the same 
issue with use all link
```shell
$ls | grep cobolt
cobolt-0.0.1.dist-info
```

**Comment by boyinggong** [comment]
@WhaleGe 

This issue should have been fixed by now. Could you try installing using the latest repo?

**Comment by yulijia** [comment]
Hi, 
I tried `pip install git+https://github.com/epurdom/cobolt.git#egg=cobolt` but still cannot install the cobolt package, any suggestions?

 ```
conda create --name cobolt python=3.7
conda activate cobolt
pip install git+https://github.com/epurdom/cobolt.git#egg=cobolt
```
> Successfully built cobolt
Installing collected packages: texttable, typing-extensions, tqdm, threadpoolctl, numpy, llvmlite, joblib, igraph, torch, scipy, python-igraph, numba, xgboost, scikit-learn, sklearn, pynndescent, umap-learn, cobolt
Successfully installed cobolt-0.0.1 igraph-0.9.10 joblib-1.1.0 llvmlite-0.38.0 numba-0.55.1 numpy-1.21.6 pynndescent-0.5.6 python-igraph-0.9.10 scikit-learn-1.0.2 scipy-1.7.3 sklearn-0.0 texttable-1.6.4 threadpoolctl-3.1.0 torch-1.11.0 tqdm-4.64.0 typing-extensions-4.2.0 umap-learn-0.5.3 xgboost-1.6.0
```
ls ./lib/python3.7/site-packages | grep cobolt
```
> cobolt-0.0.1.dist-info

**Comment by xiachenrui** [comment]
> @WhaleGe
> 
> This issue should have been fixed by now. Could you try installing using the latest repo?

I try but useless

**Comment by epurdom** [comment]
Sorry for the delay -- we had a change in people working on the package. We have made changes to the setup.py file which should hopefully fix this issue (v1.0.1 [cf5a448](https://github.com/epurdom/cobolt/commit/cf5a448c6539025346a6393c215ba329cb3a0183)). Please let us know if you have any further problems.
